@Library('olcne-pipeline') _
import com.oracle.olcne.pipeline.BranchPattern

String istio_version = "1.26.7"
String imageTag = istio_version + ''

imagePipeline(
        branchPattern: new BranchPattern(master: 'oracle/release/1.26.7', feature: '(?!^release/.*$)(^.*$)'),
        containers: [('container-registry.oracle.com/olcne/ztunnel:' + imageTag ): 'olcne/ztunnel:' + imageTag],
        platforms: [ 'ol8', 'ol9'],
        enableRepos: ['ol9_appstream', 'ol9_codeready_builder'],
        architectures: ['x86_64', 'aarch64'],
        buildScript: "sh olm/build-image.sh",
)
